### ISSUE TITLE
Merge optimizer code into web app

### ISSUE THREAD

**Issue by benpankow** [CS196Illinois/schedule-optimizer#48]
Merge Hassan's optimizer stuff into what's in the dev branch, making a new branch (48)

**Comment by 42mileslong** [comment]
Was the code finished?

**Comment by benpankow** [comment]
No but I think it'd make sense to merge his working copy into the web app instead of having it as a free-floating js file

**Comment by 42mileslong** [comment]
ahk makes sense

**Comment by 42mileslong** [comment]
Ben merged code, still not functional. See issue #52.
