### ISSUE TITLE
Make home page not awful

### ISSUE THREAD

**Issue by benpankow** [CS196Illinois/schedule-optimizer#79]
A red "This is the courses page." isn't the nicest looking home page - easy fix, idk what to though

**Comment by 42mileslong** [comment]
@AlpriElse didn't you say you were working on this?

**Comment by 42mileslong** [comment]
Looks good enough to close to me, @AlpriElse do you plan on working on this more?

If we want to, we could work on integrating tables/buttons into the new style.
